[project]
name = "try-mlx-lm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlx-lm>=0.21.4",
    "python-dotenv>=1.0.1",
]
